/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsProductIdRouteImport } from './routes/collections.$productId'

const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsProductIdRoute = CollectionsProductIdRouteImport.update({
  id: '/collections/$productId',
  path: '/collections/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/checkout': typeof CheckoutRoute
  '/heritage': typeof HeritageRoute
  '/journal': typeof JournalRoute
  '/collections/$productId': typeof CollectionsProductIdRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/checkout': typeof CheckoutRoute
  '/heritage': typeof HeritageRoute
  '/journal': typeof JournalRoute
  '/collections/$productId': typeof CollectionsProductIdRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/checkout': typeof CheckoutRoute
  '/heritage': typeof HeritageRoute
  '/journal': typeof JournalRoute
  '/collections/$productId': typeof CollectionsProductIdRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/checkout'
    | '/heritage'
    | '/journal'
    | '/collections/$productId'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/checkout'
    | '/heritage'
    | '/journal'
    | '/collections/$productId'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/checkout'
    | '/heritage'
    | '/journal'
    | '/collections/$productId'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  CheckoutRoute: typeof CheckoutRoute
  HeritageRoute: typeof HeritageRoute
  JournalRoute: typeof JournalRoute
  CollectionsProductIdRoute: typeof CollectionsProductIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$productId': {
      id: '/collections/$productId'
      path: '/collections/$productId'
      fullPath: '/collections/$productId'
      preLoaderRoute: typeof CollectionsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  CheckoutRoute: CheckoutRoute,
  HeritageRoute: HeritageRoute,
  JournalRoute: JournalRoute,
  CollectionsProductIdRoute: CollectionsProductIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
